- name: Loops
  hosts: localhost
  connection: local
  tasks:
    - name: Print fruits
      ansible.builtin.debug:
        msg: Fruit Name - {{ item }}
      loop:
        - apple
        - banana
        - orange
    - name: Print fruit with quantity
      ansible.builtin.debug:
        msg: Fruit Name - {{ item.name }}, Quantity - {{ item.quantity }}
      loop:
        - { name: apple, quantity: 10 }
        - { name: banana, quantity: 10 }
        - { name: orange, quantity: 10 }



