- name: Filters
  hosts: localhost
  connection: local
  vars:
    URL: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.zip
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: "{{ URL | split('/') | last}}"
